#!/bin/bash

/usr/local/bin/mytardis_mount $HOME/MyTardis -f 1>>$HOME/mytardis_sftp.log 2>>$HOME/mytardis_sftp-error.log &

COUNTER=0
while [  $COUNTER -lt 50 ]; do
    FILESYSTEM_TYPE=`stat -f -c '%T' $HOME/MyTardis`
    if [ $FILESYSTEM_TYPE == 'fuseblk' ]; then
        exit 0
    fi
    sleep 0.1
    let COUNTER=COUNTER+1
done

echo "$HOME/MyTardis failed to mount after 5 seconds."
exit 1


